name: ctrl_alt_tv
description: "flutter app to control a hisense infrared tv remote through an esp32 microcontroller"
publish_to: 'none' # remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

  wakelock_plus: ^1.3.2
  speech_to_text: ^7.3.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  http: ^1.1.0

  font_awesome_flutter: ^10.6.0
  permission_handler: ^11.0.0
  vosk_flutter_2: ^1.0.5
  record: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/netflix-3.svg
    - assets/icons/icons8-youtube-music.svg
    - assets/icons/amazon-prime-video-1.svg
    - assets/icons/youtube-6.svg
    - assets/icons/showmax-logo-vector.svg
    - assets/icons/dstv-logo.svg
    - assets/models/vosk-model-small-en-us-0.15.zip